version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8000"
      - "50051:50051"
      - "8181:8181"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"
  evans:
    image: heavywatal/evans
    depends_on:
      - app
    command: ["grpc", "--host", "app", "--port", "50051"]
    volumes:
      - ./internal/infra/grpc/protofiles:/protofiles